export const en = {
  appName: 'Kobciye',
  tagline: 'Premium School Management',
  dashboard: 'Dashboard',
  students: 'Students',
  teachers: 'Teachers',
  classes: 'Classes',
  attendance: 'Attendance',
  finance: 'Finance',
  payments: 'Payments',
  exams: 'Exams',
  lessons: 'Lessons',
  incidents: 'Student Incidents',
  reports: 'Reports',
  permissions: 'Permissions',
  messages: 'Messages',
  profile: 'Profile',
  settings: 'Settings',
  logout: 'Log Out',
  notifications: 'Notifications',
  subjects: 'Subjects',
  subscriptions: 'Subscriptions',
  riskScore: 'Risk Score / Early Warning',
  addStudent: 'Add Student',
  addTeacher: 'Add Teacher',
  viewAttendance: 'View Attendance',
  viewPayments: 'View Payments',
  viewReports: 'View Reports',
  viewIncidents: 'View Incidents',
  reportIncident: 'Report Incident',
  markAttendance: 'Mark Attendance',
  enterMarks: 'Enter Exam Marks',
  incidentType: 'Incident Type',
  severity: 'Severity',
  actionTaken: 'Action Taken',
  parentNotified: 'Parent Notified',
  parentResponse: 'Parent Response',
  followUpDate: 'Follow-up Date',
  status: 'Status',
  reportedBy: 'Reported By',
  witnesses: 'Witnesses',
  description: 'Description',
  teacherNote: 'Teacher Note',
  adminNote: 'Admin Note',
  low: 'Low',
  medium: 'Medium',
  high: 'High',
  critical: 'Critical',
  open: 'Open',
  underReview: 'Under Review',
  resolved: 'Resolved',
  escalated: 'Escalated',
  paid: 'Paid',
  unpaid: 'Unpaid',
  partial: 'Partial',
  free: 'Free',
  totalStudents: 'Total Students',
  totalTeachers: 'Total Teachers',
  attendanceToday: 'Attendance Today',
  monthlyRevenue: 'Monthly Revenue',
  totalSchools: 'Total Schools',
  activeSchools: 'Active Schools',
  pendingRequests: 'Pending Requests',
  suspendedSchools: 'Suspended Schools',
  activeSubscriptions: 'Active Subscriptions',
  platformRevenue: 'Platform Revenue',
  systemAlerts: 'System Alerts',
  loading: 'Loading dashboard...',
  error: 'Something went wrong. Please try again.',
  noStudents: 'No students added yet.',
  noStudentsHint: 'Add students in a later phase.',
  noIncidents: 'No incidents recorded yet.',
  noIncidentsHint: 'Student behavior records will appear here after teachers or admins add reports.',
  noData: 'No data available yet.',
  loginPlaceholder: 'Secure login will be activated in Phase 3.',
  onboardingTitle1: 'Premium School Management',
  onboardingDesc1: 'Manage students, teachers, attendance, payments and more from one powerful platform.',
  onboardingTitle2: 'Track Every Student',
  onboardingDesc2: 'Monitor attendance, exam results, behavior and fee payments for every student.',
  onboardingTitle3: 'Multi-Role Access',
  onboardingDesc3: 'Role-based dashboards for Super Admin, School Admin, Teachers, Accountants, Parents and Students.',
  getStarted: 'Get Started',
  next: 'Next',
  skip: 'Skip',
  registerSchool: 'Register Your School',
  schoolName: 'School Name',
  schoolType: 'School Type',
  region: 'Region / City',
  principalName: 'Principal Name',
  email: 'Email Address',
  phone: 'Phone Number',
  primarySchool: 'Primary School',
  secondarySchool: 'Secondary School',
  university: 'University',
  submit: 'Submit Registration',
  pricingTitle: 'Simple, Transparent Pricing',
  pricingSubtitle: 'Choose the plan that fits your school.',
  monthly: 'Monthly',
  yearly: 'Yearly',
  chooseplan: 'Choose Plan',
  search: 'Search...',
  filter: 'Filter',
  viewDetails: 'View Details',
  viewAll: 'View All',
  recentActivity: 'Recent Activity',
  quickActions: 'Quick Actions',
  myChildren: 'My Children',
  behaviorSummary: 'Behavior Summary',
  latestNotice: 'Latest Notice',
};
