export const so = {
  appName: 'Kobciye',
  tagline: 'Maamulka Dugsiga Heerka Sare',
  dashboard: 'Dashboard',
  students: 'Ardayda',
  teachers: 'Macallimiinta',
  classes: 'Fasallada',
  attendance: 'Xaadiris',
  finance: 'Maaliyadda',
  payments: 'Lacag-bixin',
  exams: 'Imtixaanada',
  lessons: 'Casharrada',
  incidents: 'Kiisaska Ardayga',
  reports: 'Warbixinta',
  permissions: 'Oggolaanshaha',
  messages: 'Fariimaha',
  profile: 'Profile-ka',
  settings: 'Goobaha',
  logout: 'Ka Bax',
  notifications: 'Ogeysiisyada',
  subjects: 'Maaddooyinka',
  subscriptions: 'Ruqsadaha',
  riskScore: 'Heerka Khatarta',
  addStudent: 'Ku Dar Arday',
  addTeacher: 'Ku Dar Macalin',
  viewAttendance: 'Arag Xaadiris',
  viewPayments: 'Arag Lacag-bixin',
  viewReports: 'Arag Warbixinta',
  viewIncidents: 'Arag Kiisaska',
  reportIncident: 'Diiwaangeli Kiis',
  markAttendance: 'Xaadirinta Calaamadee',
  enterMarks: 'Gali Natiijada Imtixaanka',
  incidentType: 'Nooca Kiiska',
  severity: 'Heerka Kiiska',
  actionTaken: 'Tallaabada La Qaaday',
  parentNotified: 'Waalid La Ogeysiiyay',
  parentResponse: 'Jawaabta Waalida',
  followUpDate: 'Taariikhda Raad-raaca',
  status: 'Xaaladda',
  reportedBy: 'Kan Soo Gudbiyay',
  witnesses: 'Markhaatiga',
  description: 'Sharaxaadda',
  teacherNote: 'Xusuusin Macalin',
  adminNote: 'Xusuusin Maamul',
  low: 'Hooseeya',
  medium: 'Dhexdhexaad',
  high: 'Sarreeya',
  critical: 'Xasaasi Ah',
  open: 'Furan',
  underReview: 'La Eegayo',
  resolved: 'La Xaliyay',
  escalated: 'Kor Loo Qaaday',
  paid: 'La Bixiyay',
  unpaid: 'Lama Bixin',
  partial: 'Qayb',
  free: 'Bilaash',
  totalStudents: 'Tirada Ardayda',
  totalTeachers: 'Tirada Macalimiinta',
  attendanceToday: 'Xaadirinta Maanta',
  monthlyRevenue: 'Lacagta Bishan',
  totalSchools: 'Dugsiyo Guud',
  activeSchools: 'Dugsiyo Firfircoon',
  pendingRequests: 'Codsiyada Sugaya',
  suspendedSchools: 'Dugsiyo Joojiyay',
  activeSubscriptions: 'Ruqsad Firfircoon',
  platformRevenue: 'Dakhliga Platform',
  systemAlerts: 'Digniinaha Nidaamka',
  loading: 'Waa la soo rarayo...',
  error: 'Wax khalad ah ayaa dhacay. Fadlan isku day mar kale.',
  noStudents: 'Ardayday weli lama darin.',
  noStudentsHint: 'Ardayda ku dar marxaladda soo socota.',
  noIncidents: 'Kiis wali lama diiwaan-galin.',
  noIncidentsHint: 'Diiwaanada dhaqanka ardayga ayaa halkan ka muuqan doona markii macalimiinta ama maamuluhu warbixinta ku daro.',
  noData: 'Xog kuma jirto hadda.',
  loginPlaceholder: 'Gelitaanka ammaan ah waxaa la shidli doonaa Marxaladda 3.',
  onboardingTitle1: 'Maamulka Dugsiga Heerka Sare',
  onboardingDesc1: 'Maamul ardayda, macalimiinta, xaadirisinta, lacag-bixinta iyo wax kale oo badan hal platform oo xooggan.',
  onboardingTitle2: 'Raadi Arday Kasta',
  onboardingDesc2: 'La socod xaadirisinta, natiijada imtixaanka, dhaqanka iyo lacag-bixinta ardayga kasta.',
  onboardingTitle3: 'Helitaan Doorka Saldhig',
  onboardingDesc3: 'Dashboard-yada ku salaysan doorka: Super Admin, Maamulaha Dugsiga, Macalimiinta, Xisaabiyaha, Waalidka iyo Ardayda.',
  getStarted: 'Bilow',
  next: 'Xiga',
  skip: 'Iska dhaaf',
  registerSchool: 'Dugsigu ku Diiwaan-galin',
  schoolName: 'Magaca Dugsiga',
  schoolType: 'Nooca Dugsiga',
  region: 'Gobolka / Magaalada',
  principalName: 'Magaca Agaasimaha',
  email: 'Cinwaanka Emaylka',
  phone: 'Lambarka Telefoonka',
  primarySchool: 'Dugsi Hoose',
  secondarySchool: 'Dugsi Sare',
  university: 'Jaamacad',
  submit: 'Gudbi Diiwaangelinta',
  pricingTitle: 'Qiimaha Fudud oo Cad',
  pricingSubtitle: 'Dooro qorshaha ku habboon dugsigaaga.',
  monthly: 'Bishii',
  yearly: 'Sanadkii',
  chooseplan: 'Dooro Qorshe',
  search: 'Raadi...',
  filter: 'Shaandee',
  viewDetails: 'Faahfaahin',
  viewAll: 'Dhamaantooda Arag',
  recentActivity: 'Hawlaha Dhowaan',
  quickActions: 'Ficilada Degdega',
  myChildren: 'Carruurteyda',
  behaviorSummary: 'Koobida Dhaqanka',
  latestNotice: 'Ogeysiiska Ugu Dambe',
};
